### ISSUE TITLE
Hosted site missing updates

### ISSUE THREAD

**Issue by denhamparry** [securekubernetes/securekubernetes#3]
Working through the demo, I noticed during the attack I noticed that the `yaml` was out of date:

```yaml
cd /tmp; cat > bitcoinero.yml <<EOF
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
...
```

When reviewing the master branch, I can see that the fix has been made to the `md` document, but these changes are not reflected in the website.

I'm part of the team working on the CTF event on Tuesday and wanted to further promote this CTF as I've found it to be really useful :smile: :+1: :100:  Thanks for setting such a high standard!
